export const images = {
    strawberry: '/images/StrawberryCharacter.webp',
    jerry: '/images/Jerry.webp',
    PapaSmurf: '/images/PapaSmurf.webp',
    Shrek: '/images/Shrek.webp',
    Tom: '/images/Tom.webp',
    duck: '/images/duck.webp',
    helloKitty: '/images/helloKitty.webp',
    mickeyMouse: '/images/mickeyMouse.webp',
    patrickStar: '/images/patrickStar.webp',
    popeye: '/images/popeye.webp',
    bunny: '/images/bunny.webp',
    scoobyDoo: '/images/scoobyDoo.webp',
    spongeBob: '/images/spongeBob.webp',
    tigger: '/images/tigger.webp',
    tweetyBird: '/images/tweetyBird.webp',
    winnieThePooh: '/images/winnieThePooh.webp',
    yogiBear: '/images/yogiBear.webp',
    mcCormick: '/images/mcCormick.webp',
};
